### ISSUE TITLE
Mob Net crashes the game

### ISSUE THREAD

**Issue by VatskiySas** [MCrafterzz/VanillaAutomated#10]
Im afraid of using mob nets now. Almost every time i release a mob, it crashes the game. For example, i took a zombified piglin from the overworld and put him in the nether. It instanly crashed after releasing him. Also this happend when i put enderman inside the lava block or just because i put piglin on the side of the block.

**Comment by MarcusElg** [comment]
Post the crash log and make sure that you are using Minecraft 1.16.2 or 1.16.3

**Comment by VatskiySas** [comment]
> Post the crash log and make sure that you are using Minecraft 1.16.2 or 1.16.3

Im using 1.16.1 version, but i have the right version of the mod and the minecraft. Mod version is 1.1.2
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 14.09.20 20:04
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at vanillaautomated.items.MobNetItem.method_7884(MobNetItem.java:93)
	at net.minecraft.class_1799.method_7981(class_1799.java:213)
	at net.minecraft.class_636.method_2896(class_636.java:332)
	at net.minecraft.class_310.method_1583(class_310.java:1425)
	at net.minecraft.class_310.method_1508(class_310.java:1659)
	at net.minecraft.class_310.method_1574(class_310.java:1507)
	at net.minecraft.class_310.method_1523(class_310.java:994)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

**Comment by MarcusElg** [comment]
Is there a reason that you aren't using 1.16.2? Most mods should support it

**Comment by VatskiySas** [comment]
> Is there a reason that you aren't using 1.16.2? Most mods should support it

So i should be using 1.16.2? If it the only way to fix that, I could do that. But is there any other way though

**Comment by MarcusElg** [comment]
> > Is there a reason that you aren't using 1.16.2? Most mods should support it
> 
> So i should be using 1.16.2? If it the only way to fix that, I could do that. But is there any other way though

It would be great if you could try V. 1.1.4 to see if the issue is still present because it has never crashed for me.

The thing is that it doesn't make much sense to support an old minor version as 1.16.1 and 1.16.3 are so similar. The source code is available though.

**Comment by VatskiySas** [comment]
> > > Is there a reason that you aren't using 1.16.2? Most mods should support it
> > 
> > 
> > So i should be using 1.16.2? If it the only way to fix that, I could do that. But is there any other way though
> 
> It would be great if you could try V. 1.1.4 to see if the issue is still present because it has never crashed for me.
> 
> The thing is that it doesn't make much sense to support an old minor version as 1.16.1 and 1.16.3 are so similar. The source code is available though.

Okay. Thanks for replying so fast. I guess im moving to a better version :>
