### ISSUE TITLE
imma cry

### ISSUE THREAD

**Issue by VatskiySas** [MCrafterzz/VanillaAutomated#11]
Nothing changed. I had to find every mod in 1.16.2 and after all of this it still doesnt work...
---- Minecraft Crash Report ----
// You're mean.

Time: 14.09.20 21:32
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at vanillaautomated.items.MobNetItem.method_7884(MobNetItem.java:93)
	at net.minecraft.class_1799.method_7981(class_1799.java:227)
	at net.minecraft.class_636.method_2896(class_636.java:328)
	at net.minecraft.class_310.method_1583(class_310.java:1427)
	at net.minecraft.class_310.method_1508(class_310.java:1657)
	at net.minecraft.class_310.method_1574(class_310.java:1509)
	at net.minecraft.class_310.method_1523(class_310.java:996)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at vanillaautomated.items.MobNetItem.method_7884(MobNetItem.java:93)
	at net.minecraft.class_1799.method_7981(class_1799.java:227)
	at net.minecraft.class_636.method_2896(class_636.java:328)
	at net.minecraft.class_310.method_1583(class_310.java:1427)
	at net.minecraft.class_310.method_1508(class_310.java:1657)

-- Affected level --
Details:
	All players: 1 total; [class_746['EuclidovSas'/1885, l='ClientLevel', x=-169.70, y=64.18, z=19.79]]
	Chunk stats: Client Chunk Cache: 841, 575
	Level dimension: minecraft:overworld
	Level spawn location: World: (-176,66,0), Chunk: (at 0,4,0 in -11,0; contains blocks -176,0,0 to -161,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 435 game time, 435 day time
	Server brand: fabric
	Server type: Integra

**Comment by MarcusElg** [comment]
I'll look into it tomorrow morning

**Comment by VatskiySas** [comment]
> I'll look into it tomorrow morning

tyvm <3

**Comment by MarcusElg** [comment]
Can replicate with the pigmen. Only seems to happen for some mobs, slimes for example work fine.

**Comment by MarcusElg** [comment]
Ok so I've made some changes. It does sometimes post an error message in the log but it doesn't crash and the mob net seams to work as exspected. So try the new version when its released later today. So I'm closing this for now but feel free to reopen if there is some case where the fix doesn't work.

**Comment by MarcusElg** [comment]
https://www.curseforge.com/minecraft/mc-mods/vanilla-automated/files/3057576
