### ISSUE TITLE
Recipe parsing error on startup

### ISSUE THREAD

**Issue by Greg-J** [MCrafterzz/VanillaAutomated#8]
`[11:01:45 ERROR]: Parsing error loading recipe vanillaautomated:iridium_dust
com.google.gson.JsonSyntaxException: Unknown item 'c:iridium_dust'
	at net.minecraft.class_1869.method_17878(class_1869.java:233) ~[intermediary-server.jar:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.class_1869.method_8155(class_1869.java:233) ~[intermediary-server.jar:?]
	at vanillaautomated.recipes.CrusherRecipeSerializer.read(CrusherRecipeSerializer.java:30) ~[vanillautomated-1.1.2.jar:?]
	at vanillaautomated.recipes.CrusherRecipeSerializer.method_8121(CrusherRecipeSerializer.java:14) ~[vanillautomated-1.1.2.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_261]
[11:01:45 ERROR]: Parsing error loading recipe vanillaautomated:palladium_dust
com.google.gson.JsonSyntaxException: Unknown item 'c:palladium_dust'
	at net.minecraft.class_1869.method_17878(class_1869.java:233) ~[intermediary-server.jar:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.class_1869.method_8155(class_1869.java:233) ~[intermediary-server.jar:?]
	at vanillaautomated.recipes.CrusherRecipeSerializer.read(CrusherRecipeSerializer.java:30) ~[vanillautomated-1.1.2.jar:?]
	at vanillaautomated.recipes.CrusherRecipeSerializer.method_8121(CrusherRecipeSerializer.java:14) ~[vanillautomated-1.1.2.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_261]
[11:01:45 ERROR]: Parsing error loading recipe vanillaautomated:gold_dust
com.google.gson.JsonSyntaxException: Unknown item 'c:gold_dust'
	at net.minecraft.class_1869.method_17878(class_1869.java:233) ~[intermediary-server.jar:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.class_1869.method_8155(class_1869.java:233) ~[intermediary-server.jar:?]
	at vanillaautomated.recipes.CrusherRecipeSerializer.read(CrusherRecipeSerializer.java:30) ~[vanillautomated-1.1.2.jar:?]
	at vanillaautomated.recipes.CrusherRecipeSerializer.method_8121(CrusherRecipeSerializer.java:14) ~[vanillautomated-1.1.2.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_261]
[11:01:45 ERROR]: Parsing error loading recipe vanillaautomated:titanium_dust
com.google.gson.JsonSyntaxException: Unknown item 'c:titanium_dust'
	at net.minecraft.class_1869.method_17878(class_1869.java:233) ~[intermediary-server.jar:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.class_1869.method_8155(class_1869.java:233) ~[intermediary-server.jar:?]
	at vanillaautomated.recipes.CrusherRecipeSerializer.read(CrusherRecipeSerializer.java:30) ~[vanillautomated-1.1.2.jar:?]
	at vanillaautomated.recipes.CrusherRecipeSerializer.method_8121(CrusherRecipeSerializer.java:14) ~[vanillautomated-1.1.2.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_261]`

Loading the following mods:

`[11:01:25] [main/INFO]: [FabricLoader] Loading 167 mods: fermion@2.1.191, fabric-keybindings-v0@0.2.0+3fa9f7c502, couplings@1.3.1, aopalliance_aopalliance@1.0, fermion-orientation@1.0.180-snapshot, chains@1.1.1, rgbblocks@2.1.2, fabricloader@0.9.0+build.204, trinkets@2.6.3, com_fasterxml_jackson_core_jackson-annotations@2.9.0, euclid@1.1, verticalslabs@1.3.0, fabric-dimensions-v1@1.0.0+a71b305302, kibe@1.1.11-BETA, betternether@3.4.3, com_google_inject_guice@4.2.3, fermion-modkeys@1.8.180-snapshot, fabric-api-base@0.1.3+12a8474c7c, rpgstats@2.1.0+1.16.1, special-circumstances@1.6.191, org_jetbrains_exposed_exposed-core@0.23.1, chunkactivator@2.1.0+mc1.16.1, cotton-cauldron@1.0.4, lambdynlights@1.2.2+1.16.1, adabraniummod@1.1.5.1, cardinal-components-level@2.4.0-nightly.1.16-rc1.build.2, economy@1.2, org_jetbrains_kotlin_kotlin-stdlib@1.3.72, decorative@2.0.0 - Summer 2020 Update, com_moandjiezana_toml_toml4j@0.7.2, playerabilitylib@1.2.0, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8902, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.3.72, fabric@0.15.1+build.380-1.16.1, org_slf4j_slf4j-api@1.8.0-beta1, fabric-diagonal-panes@0.3.0, fabric-networking-v0@0.1.10+e00ecb5f02, cotton-config@1.0.0-rc.7, libmultipart@0.4.0, fabric-screen-handler-api-v1@1.1.0+97324d1102, simpledrawers@1.8.0-1.16.1, dungeons@1.2.1+1.16.1, phosphor@0.6.0+build.7, mysql_mysql-connector-java@5.1.46, hookshot@5.0, fabric-tool-attribute-api-v1@1.1.4+5794386e02, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.3.72, cloth-client-events-v0@1.0.4, org_apache_commons_commons-compress@1.19, blockus@1.6.2, fabric-biomes-v1@0.2.7+059ea86602, fabric-crash-report-info-v1@0.1.2+b7f9825d02, fabric-events-interaction-v0@0.3.3+7066030f02, identity@1.4.0-beta-1.16, fabric-language-kotlin@1.3.72+build.1, origins@1.16-0.2.3, fabric-key-binding-api-v1@1.0.1+f404f3be02, cloth-config2@4.6.0, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.3.7, org_tukaani_xz@1.8, fabric-resource-loader-v0@0.2.6+f41e209802, org_jetbrains_kotlin_kotlin-reflect@1.3.72, trapexpansion@1.3.2, universalcomponents@0.7.2+1.16-pre2, worldedit@7.2.0-beta-02+d10d7d6, cardinal-components-entity@2.4.1, magna@1.1.1-1.16.1, fabric-commands-v0@0.2.0+52d3083602, fabric-registry-sync-v0@0.3.8+7dba2d6c02, platos@1.2.3, adorn@1.9.1+1.16.1, cardinal-components-base@2.4.1, exotic-matter@2.4.343, lightoverlay@5.4.1, fabric-mining-levels-v0@0.1.2+b764ce9902, cotton-player-events@1.0.2, toms_storage@1.1.0, libmultipart_deps_container@0.4.0, fabric-models-v0@0.1.0+dfdb52d602, fabric-item-groups-v0@0.2.0+438f963602, com_fasterxml_jackson_module_jackson-module-kotlin@2.9.0, org_jetbrains_annotations@17.0.0, fabric-renderer-api-v1@0.2.13+eae12eb802, parchment@1.0.2+1.15.2, libcd@2.5.0+1.16.1, cardinal-components-block@2.4.0-nightly.1.16-rc1.build.2, cotton@1.0.5, org_jetbrains_kotlinx_kotlinx-coroutines-core@1.3.7, vanilla-hammers@1.10.1-1.16.1, cavebiomes@0.2.3, lightblock@1.16+1.1.0+build.8, com_github_shevek_parallelgzip@master-SNAPSHOT, fabric-containers-v0@0.1.8+045df74f02, lithium@0.5.1, fabric-object-builder-api-v1@1.5.6+a2d21ddd02, convth@0.8.1, ringsofascension@1.0.3, org_postgresql_postgresql@42.2.2, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d02, essentials-base@0.2.3+1.16.1, campanion@1.1.12+build.33, cardinal-components-item@2.4.0, fabric-textures-v0@1.0.4+eae12eb802, fabric-rendering-fluids-v1@0.1.8+b7084faa02, reach-entity-attributes@1.0.1, javax_inject_javax_inject@1, com_fasterxml_jackson_core_jackson-databind@2.9.0, cotton-logging@1.0.0-rc.4, fabric-lifecycle-events-v1@1.1.0+013e49d202, cardinal-components-chunk@2.4.1, com_fasterxml_jackson_dataformat_jackson-dataformat-yaml@2.9.0, cardinal-components-util@2.4.0-nightly.1.16-rc1.build.2, fabric-renderer-registries-v1@2.0.1+5a0f9a6002, fabric-loot-tables-v1@1.0.0+386eb69e02, com_fasterxml_jackson_core_jackson-core@2.9.0, fabric-particles-v1@0.2.1+0a6f2a7002, tomsfabriclibs@1.0.1, libblockattributes_core@0.7.0, vanilla_parts@1.1.3+1.16.1, org_jetbrains_exposed_exposed-jdbc@0.23.1, libnetworkstack@0.4.0, no_fog@1.0.0-beta.4+1.16.1, slotlink@0.3.5+minecraft-1.16.1, minecraft@1.16.1, fabric-networking-blockentity-v0@0.2.5+b50ffc7b02, exotic-art-core@1.0.341, woolplates@1.0.1, illuminations@0.5.1, jankson@3.0.0+j1.2.0, cloth-basic-math@0.5.1, fabric-command-api-v1@1.0.8+5ce5339802, cotton-commons@1.0.4, fabric-renderer-indigo@0.3.3+0a55f37902, spinnery@3.1.12, cotton-datapack@1.0.5, roughlyenoughitems@4.10.0, fabric-item-api-v1@1.0.0+16acbe5b02, libgui@2.1.1+1.16.1, cardinal-components@2.4.0-nightly.1.16-rc1.build.2, fabric-rendering-v0@1.1.0+5341049002, fabric-rendering-v1@1.1.2+346247d702, spruceui@1.5.8, sit@1.16.1-7, autoconfig1u@3.2.0-unstable, winged@1.16-1.2, fabric-content-registries-v0@0.1.9+059ea86602, fabric-tag-extensions-v0@0.2.7+a4c57d8e02, cardinal-components-world@2.4.0-nightly.1.16-rc1.build.2, mooblooms@1.3.1, org_xerial_sqlite-jdbc@3.28.0, blue_endless_jankson@1.2.0, fabric-furnaces@1.3.1-1.16.1, gravestones@1.4.0, inmis@1.2.0-1.16.1, xb@1.4.142, org_jetbrains_exposed_exposed-java-time@0.23.1, hotm@1.16.1-0.1.2, textile_backup@1.3.0-1.16.1, byg@1.0.9, voxelmap@1.10.4, trade@1.1.0, fabric-events-lifecycle-v0@0.2.0+16acbe5b02, libstructure@1.3, vanillaautomated@1.1.2, fabric-object-builders-v0@0.6.1+a2d21ddd02, org_yaml_snakeyaml@1.26, fermion-varia@2.1.191`

**Comment by MarcusElg** [comment]
I know. It is like that if you don't have cotton resources installed. It doesn't affect anything so just ignore it. I will fix it when updating to 1.16.2 as that adds optional tags
